### PR TITLE
Proposition to fix #13

### LINKED ISSUE #13: table_row_id_fieldname does not work as expect with details
Hello,

Hope everything well.
Just give a try to the last version (3.2.3). I got a table with a pk field id named "rel_id" (Not id).

I setup the 
```
table_row_id_fieldname = 'red_id'
```

And i got this message when i click on the plus

```
django.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. 
Choices are: red_available, red_comp, red_compname, red_description, red_id,
```

Misunderstanding from my side ?

Thanks for help.

Regards

### PR DESCRIPTION
**Pull request by tboulogne**
Hello,

Find my proposal to answer to my case #13 :-).
For remembrance : details row consider pk_field is always id. So does not work, if the pk_field is different.

I use **table_row_id_fieldname** to customize the pk_field for details row.

Let me know.

Regards,

### CODE REVIEW

**Comment by morlandi** [comment]
Hello @tboulogne ,
sorry to keep you waiting .. I've been quite busy on this project: https://github.com/morlandi/django-upload-form, which is currently draining all the time I can devote to open source projects.
On the other side, please rest assured I will not make any change to django-datatables-view before reviewing your PR.
First, I'ld like to add an example project to the package to test it interactively.
Then, I would like to discuss a couple of issues with you:
1) as far as I can see, you're coping with a PK with a name other than "id"; however, Django already has a solution for that: using "pk" as field name. Wouldn't be nice to apply the very same convention in the package?
2) `initialize_table()` accepts an optional `extra_data` dictionary which is then propagated everywhere is JS code. Can we think about saving the optional "custom_id" attribute there? The application might need to add more custom parameters other than "custom_id", and a more generic solution could be helpful

**Comment by tboulogne** [comment]
Hello @morlandi 

No problem :-). Will give your project a try. I wrote some code like that with [dropzonejs](https://www.dropzonejs.com)

> as far as I can see, you're coping with a PK with a name other than "id"; however, Django already has a solution for that: using "pk" as field name. Wouldn't be nice to apply the very same convention in the package?
not understand your meaning

>initialize_table() accepts an optional extra_data dictionary which is then propagated everywhere is JS code. Can we think about saving the optional "custom_id" attribute there? The application might need to add more custom parameters other than "custom_id", and a more generic solution could be helpful

Why not. 

I wrote some code for generic creation of edit/update form with buttons on last column of datatables. I schedule to discuss this with you after some holidays :-).

**Comment by morlandi** [comment]
dropzonejs seems amazing !  thank you ;)

**Comment by tboulogne** [comment]
you'e welcome :-)

**Comment by morlandi** [comment]
> I wrote some code for generic creation of edit/update form with buttons on last column of datatables. I schedule to discuss this with you after some holidays :-).

I would be really interested in discussing this with you.
I did some research on this subject, summarized here:

https://editing-django-models-in-the-frontend.readthedocs.io/en/latest/

and here:

https://github.com/morlandi/editing-django-models-in-the-frontend

and more recently a reusable Django app:

https://github.com/morlandi/django-frontend-forms


I close this PR since has been superseded ; see my final comment in #13

**Pull request closed without merging**
