### PR TITLE
Make it works with manytomany field

### PR DESCRIPTION
**Pull request by tboulogne**
As select_related does not works with manytomany fields (i search a long time before find this...)
i suggest you use prefetch_related.

For remembering :
> select_related (join in database)
> prefetch_related (join in python)

regards

### CODE REVIEW

**Comment by morlandi** [comment]
Hello @tboulogne ... 
interesting point ;)

The library is trying to optimize data extraction in a generic way ... as such, some limitations have to be expected; please consider you can always disable this optimization on a per-class basis with the **disable_queryset_optimization** attribute, then provide your own by overriding **get_initial_queryset()**

I do agree that in some cases prefetch_related() is more appropriate than select_related(), but can we safely replace everywhere selected_related() with prefetch_related() ? If not, this would be a backward incompatible change, and could break existing code.

**Comment by tboulogne** [comment]
Hello @morlandi 

disable_queryset_optimization > .... not so fun to rewrite a query_set :-).

Perhaps we could test field and apply prefetch_related only if needed ? And As you are talking about backward compatibility.... in anycase select_related break compatibility.

I was on 2.2.3 and update to latest... and problem starts :-). So we need to make something !

**Comment by tboulogne** [comment]
[UPDATE], for now, replacing just in view, solved my problem. So we could try only view for now.

**Comment by morlandi** [comment]
> I was on 2.2.3 and update to latest... and problem starts :-)

You're right, that was a mistake !
I should have assigned True as the default value for DATATABLES_VIEW_DISABLE_QUERYSET_OPTIMIZATION.

 Optimization is not always required; I just happened to optimize some queryset here and there, that collected a "common pattern" for the most general cases. When a problem arises tor a specific table, I disable the optimization for that specific view.
  
> Perhaps we could test field and apply prefetch_related only if needed ?

This is probably the best way to go.
Please give me some time to think about it ... I will come back to this issue as soon as I will have the chance to test it in a real case

**Comment by tboulogne** [comment]
@morlandi for now:
```
disable_queryset_optimization = True
```
on the view did the tricks.

Thanks for tips :-)

**Comment by morlandi** [comment]
@tboulogne I'm going to close this PR and open an issue instead.
Thanks for suggestion ;)

**Pull request closed without merging**
