### PR TITLE
Add getCookie

### PR DESCRIPTION
**Pull request by tboulogne**
getCookie is called on line 296 but missing.

### CODE REVIEW

**Comment by morlandi** [comment]
Good catch !
I happen to always include a getCookie() implementation in my projects ;)

I'm going to replace it with this more concise variant:

```
function getCookie(name) {
    var value = '; ' + document.cookie,
        parts = value.split('; ' + name + '=');
    if (parts.length == 2) return parts.pop().split(';').shift();
}

```
which I grabbed somewhere many time ago; I guess they're functionally equivalent ;)
Thank you @tboulogne

**Comment by morlandi** [comment]
While I'm at it ... I replaced the ajax GET call with a POST one just to have a more terse output in the console window during development ;)

**Comment by tboulogne** [comment]
okay :-)

**Comment by tboulogne** [comment]
i forgot to mention that utils.js is not store into static on ./manage collectstatic.

got a file datatables_utils.js instead with only 2 functions.

**Comment by morlandi** [comment]
mmhhh ... sometime ago I moved 'static/datatables_utils.js' to 'static/datatables_view/js/utils.js' and similarly the shared css from somewhere to 'static/datatables_view/css/styles.css', to have a single common "static namespace" for the app ... I'll check the consequences of this on deployment in the next few days and come back to you on this issue.

Since MANIFEST.in states:

`recursive-include datatables_view/static *`

everything should be OK for `collectstatic`, but let me check this ;)

**Comment by morlandi** [comment]
@tboulogne I just tagged a new release `v2.2.5` since I needed the possibility to optionally specify extra options for table initialisation, so I  checked the "utils.js issue".

Before deployment I had this on the target production host, probably as a result of previous installations:

```
$ tree static/datatables_view/
static/datatables_view/
├── css
│   └── style.css
├── images
│   ├── details_close.png
│   └── details_open.png
└── js
    ├── datatables_utils.js
    └── utils.js
```

I do believe that the redundant file `datatables_utils.js` is useless (but also harmless).

I manually removed it (actually, the whole `static/datatables_view/` folder), and after deployment I found this:

```
static/datatables_view/
├── css
│   └── style.css
├── images
│   ├── details_close.png
│   └── details_open.png
└── js
    └── utils.js
```

The `utils.js` file seems in good shape:

```
$ head static/datatables_view/js/utils.js
'use strict';

window.DatatablesViewUtils = (function() {

    //var _search_icon_html = '<div style="border: 1px solid #ccc; text-align: center;">?</div>';
    var _options = {};

    var _html_daterange_widget =
        'From: <input type="date" id="date_from" class="datepicker">' +
        'To: <input type="date" id="date_to" class="datepicker">';
```

```
$ tail static/datatables_view/js/utils.js
    }

    return {
        init: init,
        initialize_table: initialize_table,
        after_table_initialization: after_table_initialization,
        adjust_table_columns: adjust_table_columns
    };

})();
```

I also should mention that during the deployment process I run `manage.py compress` after `manage.py collectstatic`, but that shouldn't matter.

Please let me know if you still notice some suspect behaviour with collectstatic ;)

**Comment by tboulogne** [comment]
great ! Thanks.

I let you know.

Regards

**Pull request merged**
