### PR TITLE
treat exception on Naive Date

### PR DESCRIPTION
**Pull request by tboulogne**
Hello,
Thanks for this project.

A little contribs on format date with TZ.

Thanks to apply

### CODE REVIEW

**Comment by morlandi** [comment]
Thank you @tboulogne 

Shouldn't you specify `custom_id` explicitly where `datatables_load_row_details()` gets invoked, inside `datatables_bind_row_tools()` body ?

**Comment by tboulogne** [comment]
Hello,

Did not understand your point.

**datatables_bind_row_tools** is the one you call just after initialized datatables. So i could pass my custom_id (a serial number, a name, ….) there and impac**t render_row_details()** query accordingly.

**Comment by morlandi** [comment]
But shouldn't line 14 be changed from:

             row.child(datatables_load_row_details(row.data(), url), 'details').show('slow');
to 

             row.child(datatables_load_row_details(row.data(), url, custom_id), 'details').show('slow');

?

**Comment by tboulogne** [comment]
you're right. fix
(i made my change on a local and manualy copy with error. sorry)

**Comment by morlandi** [comment]
Thank you @tboulogne for contribution.
Just merged.
I only adjusted the default timezone from 'Europe/Paris' to 'UTC' which seems more neutral, and as such more appropriate as default value when not specified in project settings

**Comment by tboulogne** [comment]
You’re welcome. No problem for the timezone, It was just a wink ;-)

Thierry BOULOGNE
06 43 18 31 19

**Comment by morlandi** [comment]
Hello @tboulogne ... FYI I'm doing a major refactoring (branch "version2") and I happen to face an "AttributeError: 'datetime.date' object has no attribute 'tzinfo'" exception upon receiving a datetime.date object (instead of datetime.datetime).
To proceed with my work I temporarily handled it this way:

https://github.com/morlandi/django-datatables-view/commit/186885704a340aec6cfca5876d6d8fb37dab74f5

Do you have any suggestion for better handling ? ;)
Ciao, Mario

**Comment by tboulogne** [comment]
Hello @morlandi 

I think USE_TZ is True into your settings.
 
One time i face similar issue. **datetime** could take a **tz** attribute. I usually manage :
```
today = datetime.now(tz=pytz.UTC)
```
Hope it could help :-).

**Comment by morlandi** [comment]
Thank you @tboulogne ... I confirm that USE_TZ is True in my settings ... however, on second though, I wonder whether tzinfo does even make any sense for a datetetime.date object; probably not !

    >>> pytz.timezone("Europe/Rome").localize(datetime.datetime.utcnow()).tzinfo
    <DstTzInfo 'Europe/Rome' CET+1:00:00 STD>
    >>> pytz.timezone("Europe/Rome").localize(datetime.datetime.utcnow()).date().tzinfo
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'datetime.date' object has no attribute 'tzinfo'
    >>>

**Comment by tboulogne** [comment]
You don't have same hour from Los Angeles and Roma. 2am from Roma 16/03 mean something like 
21pm 15/03 from Los Angeles :-).

So even for a date tzinfo make sense with datetime module.

**Comment by morlandi** [comment]
yes, but how could you convert a date object between timezones having no time information available ?

**Comment by tboulogne** [comment]
convert datetime.date to datetime.datetime ?

Probably you will have (2013-09-01 00:00:00Txx), so you will have TZINFO.

**Comment by morlandi** [comment]
My doubt is: given a date, with no time information, how could you decide whether to switch the day or not when moving between two timezones ? With datetime.datetime, the "threshold" comes from the time. When "downgrading" to a datetime.date, you lack that information

**Comment by tboulogne** [comment]
I don’t understand what you mean exactly, but let’s keep it simple :-)

Into settings.py we probably have USE_TZ and TIME_ZONE.

I think the date will be consider into the TIME_ZONE.

**Pull request merged**
